# Generated by Django 2.1.5 on 2019-02-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenapp', '0002_auto_20190208_0514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('wins', models.IntegerField(verbose_name='Juegos ganados')),
                ('losses', models.IntegerField(verbose_name='Juegos perdidos')),
                ('draws', models.IntegerField(verbose_name='Juegos empatados')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.CharField(max_length=100, null=True, verbose_name='Equipo'),
        ),
        migrations.AddField(
            model_name='player',
            name='team_link',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='examenapp.Team'),
        ),
    ]
