# Generated by Django 2.1.5 on 2019-02-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenapp', '0003_auto_20190208_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre de equipo'),
        ),
    ]
