# Generated by Django 2.1.5 on 2019-02-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenapp', '0004_auto_20190208_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('link', models.ForeignKey(on_delete='CASCADE', to='examenapp.Team')),
            ],
        ),
    ]
