# Generated by Django 2.1.5 on 2019-02-09 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenapp', '0005_stadium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stadium',
            name='link',
        ),
        migrations.AlterField(
            model_name='stadium',
            name='capacity',
            field=models.IntegerField(verbose_name='Capacidad'),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
